// src/components/ArticleView.tsx
import React from 'react';
import Markdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Article } from '../types';
import { Edit2, Trash2, Calendar, Tag, Clock } from 'lucide-react';
import { format } from 'date-fns';

interface ArticleViewProps {
  article: Article;
  onEdit: () => void;
  onDelete: () => void;
}

export const ArticleView: React.FC<ArticleViewProps> = ({
  article,
  onEdit,
  onDelete,
}) => {
  return (
    <div className="flex-1 h-screen overflow-y-auto bg-white">
      <div className="max-w-4xl mx-auto px-8 py-12">
        <div className="flex items-start justify-between mb-8">
          <div className="space-y-4">
            <div className="flex items-center gap-4 text-xs font-medium text-zinc-400">
              <span className="flex items-center gap-1.5 px-2 py-1 bg-zinc-100 rounded text-zinc-600">
                <Tag className="w-3 h-3" />
                {article.category || 'General'}
              </span>
              <span className="flex items-center gap-1.5">
                <Calendar className="w-3 h-3" />
                {article.created_at ? format(new Date(article.created_at), 'MMM d, yyyy') : 'Recently'}
              </span>
              <span className="flex items-center gap-1.5">
                <Clock className="w-3 h-3" />
                Updated {article.updated_at ? format(new Date(article.updated_at), 'MMM d, yyyy') : 'Recently'}
              </span>
            </div>
            <h1 className="text-4xl font-extrabold text-zinc-900 tracking-tight">
              {article.title || 'Untitled Article'}
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onEdit}
              className="p-2 rounded-lg hover:bg-zinc-100 text-zinc-500 hover:text-indigo-600 transition-all"
              title="Edit Article"
            >
              <Edit2 className="w-5 h-5" />
            </button>
            <button
              onClick={() => {
                if (confirm('Are you sure you want to delete this article?')) {
                  onDelete();
                }
              }}
              className="p-2 rounded-lg hover:bg-zinc-100 text-zinc-500 hover:text-red-600 transition-all"
              title="Delete Article"
            >
              <Trash2 className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="markdown-body prose-custom">
          <Markdown
            components={{
              code({ node, inline, className, children, ...props }: any) {
                const match = /language-(\w+)/.exec(className || '');
                return !inline && match ? (
                  <div className="my-6 rounded-xl overflow-hidden shadow-lg border border-zinc-800">
                    <div className="bg-zinc-800 px-4 py-2 text-xs text-zinc-400 font-mono flex justify-between items-center">
                      <span>{match[1]}</span>
                      <button 
                        onClick={() => navigator.clipboard.writeText(String(children))}
                        className="hover:text-white transition-colors"
                      >
                        Copy
                      </button>
                    </div>
                    <SyntaxHighlighter
                      style={vscDarkPlus}
                      language={match[1]}
                      PreTag="div"
                      customStyle={{
                        margin: 0,
                        padding: '1.5rem',
                        fontSize: '0.9rem',
                        lineHeight: '1.6',
                      }}
                      {...props}
                    >
                      {String(children).replace(/\n$/, '')}
                    </SyntaxHighlighter>
                  </div>
                ) : (
                  <code className={className} {...props}>
                    {children}
                  </code>
                );
              },
            }}
          >
            {article.content}
          </Markdown>
        </div>
      </div>
    </div>
  );
};

// src/components/ArticleView.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Article } from '../types';
import { Edit2, Trash2, Calendar, Tag, Clock } from 'lucide-vue-next';
import MarkdownIt from 'markdown-it';
import hljs from 'highlight.js';
import 'highlight.js/styles/vs2015.css';

const props = defineProps<{
  article: Article;
}>();

const emit = defineEmits<{
  (e: 'edit'): void;
  (e: 'delete'): void;
}>();

const md = new MarkdownIt({
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return '<pre class="hljs"><code>' +
               hljs.highlight(str, { language: lang, ignoreIllegals: true }).value +
               '</code></pre>';
      } catch (__) {}
    }
    return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
  }
});

const renderedContent = computed(() => {
  return md.render(props.article.content || '');
});

const formatDate = (dateString?: string) => {
  if (!dateString) return 'Recently';
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
};

const handleDelete = () => {
  if (confirm('Are you sure you want to delete this article?')) {
    emit('delete');
  }
};
</script>

<template>
  <div class="flex-1 h-screen overflow-y-auto bg-white">
    <div class="max-w-4xl mx-auto px-8 py-12">
      <div class="flex items-start justify-between mb-8">
        <div class="space-y-4">
          <div class="flex items-center gap-4 text-xs font-medium text-zinc-400">
            <span class="flex items-center gap-1.5 px-2 py-1 bg-zinc-100 rounded text-zinc-600">
              <Tag class="w-3 h-3" />
              {{ article.category || 'General' }}
            </span>
            <span class="flex items-center gap-1.5">
              <Calendar class="w-3 h-3" />
              {{ formatDate(article.created_at) }}
            </span>
            <span class="flex items-center gap-1.5">
              <Clock class="w-3 h-3" />
              Updated {{ formatDate(article.updated_at) }}
            </span>
          </div>
          <h1 class="text-4xl font-extrabold text-zinc-900 tracking-tight">
            {{ article.title || 'Untitled Article' }}
          </h1>
        </div>
        <div class="flex items-center gap-2">
          <button
            @click="emit('edit')"
            class="p-2 rounded-lg hover:bg-zinc-100 text-zinc-500 hover:text-indigo-600 transition-all"
            title="Edit Article"
          >
            <Edit2 class="w-5 h-5" />
          </button>
          <button
            @click="handleDelete"
            class="p-2 rounded-lg hover:bg-zinc-100 text-zinc-500 hover:text-red-600 transition-all"
            title="Delete Article"
          >
            <Trash2 class="w-5 h-5" />
          </button>
        </div>
      </div>

      <div class="markdown-body prose-custom" v-html="renderedContent"></div>
    </div>
  </div>
</template>

<style scoped>
.prose-custom :deep(pre.hljs) {
  margin: 1.5rem 0;
  padding: 1.5rem;
  border-radius: 0.75rem;
  overflow: auto;
  box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  border: 1px solid #27272a;
  background-color: #27272a;
  font-size: 0.9rem;
  line-height: 1.6;
}
.prose-custom :deep(code) {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
</style>
